### ISSUE TITLE
提示config导入错误，默认的conig.py文件需要写哪些内容···

### ISSUE THREAD

**Issue by neoyoung** [shr1213/PersonalHomepage#2]
提示config导入错误，默认的conig.py文件需要写哪些内容···

**Comment by shr1213** [comment]
> 提示config导入错误，默认的conig.py文件需要写哪些内容···

hi，在”PersonalHomepage/backend/app/“目录下已经新增了配置文件的demo，去掉”_demo“后就可以使用了
