### ISSUE TITLE
有部署安装说明不

### ISSUE THREAD

**Issue by leslieyin** [shr1213/PersonalHomepage#8]
大佬您好，这个有部署安装的文档不

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by shr1213** [comment]
> 大佬您好，这个有部署安装的文档不
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

大佬好，根目录有一个start.py，用python3运行它就好，里边会有提示
